source 'https://rubygems.org'

# Rails default gems
# -----------------------------------------------------------------------------
gem 'rails', '4.1.1'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'spring', group: :development


# Server and caching
# -----------------------------------------------------------------------------
gem 'unicorn'
gem 'dalli'


# Templates and assets
# -----------------------------------------------------------------------------
gem 'haml-rails'
gem 'compass-rails'
gem 'dragonfly'


# Testing
# -----------------------------------------------------------------------------
group :development do
  gem 'guard-rspec', require: false
  gem 'guard-cucumber'
end

group :test do
  gem 'database_cleaner'
  gem 'shoulda-matchers', require: false
  gem 'cucumber-rails', require: false
  gem 'capybara'
  gem 'launchy'
  gem 'faker'
end

group :development, :test do
  gem 'pry-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end


# Optional
# -----------------------------------------------------------------------------
gem 'awesome_print'
gem 'draper'
gem 'yard'
# gem 'annotate'

